# Stage 1
FROM python:3.9 AS builder

RUN pip install poetry==1.6.1

COPY . /app
WORKDIR /app

RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-cache --without dev

# Stage 2
FROM python:3.9-slim

WORKDIR /app

COPY --from=builder /usr/local/lib/python3.9/site-packages /usr/local/lib/python3.9/site-packages
COPY --from=builder /app /app

CMD ["python", "week1/main.py"]
